#!/bin/sh
set -x

# Test whether NVIDIA's libGL.so.1 is working and if it doesn't work,
# fallback to free implementation of the OpenGL API (libgl1-mesa-glx)
glxinfo >/dev/null 2>&1 || export LD_LIBRARY_PATH=/usr/lib/i386-linux-gnu/mesa
steam $@
